"""initial

Revision ID: 58e359cf2d19
Revises: 554bb6097456
Create Date: 2020-11-04 15:55:34.056913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e359cf2d19'
down_revision = '554bb6097456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('passport', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voters')
    # ### end Alembic commands ###
