"""empty message

Revision ID: 68f566ea5be3
Revises: efa991721fd7
Create Date: 2020-11-04 18:37:04.005532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f566ea5be3'
down_revision = 'efa991721fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'voters', ['passport'])
    op.create_unique_constraint(None, 'voters', ['national_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voters', type_='unique')
    op.drop_constraint(None, 'voters', type_='unique')
    # ### end Alembic commands ###
