"""initial

Revision ID: 82118ab85149
Revises: 3ff3a95e2699
Create Date: 2020-11-04 15:33:09.043386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82118ab85149'
down_revision = '3ff3a95e2699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('voted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters', 'voted')
    # ### end Alembic commands ###
