"""empty message

Revision ID: 8e9bfa1becb3
Revises: a3aff1e64f51
Create Date: 2020-11-05 19:29:06.389130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9bfa1becb3'
down_revision = 'a3aff1e64f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('party_name', sa.String(), nullable=False),
    sa.Column('party_logo_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('party_name')
    )
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('passport', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('passport')
    )
    op.create_table('governors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_name'], ['parties.party_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=255), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_name'], ['parties.party_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_name'], ['parties.party_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=255), nullable=True),
    sa.Column('president_id', sa.Integer(), nullable=True),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_name'], ['parties.party_name'], ),
    sa.ForeignKeyConstraint(['president_id'], ['presidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deputies')
    op.drop_table('senators')
    op.drop_table('presidents')
    op.drop_table('governors')
    op.drop_table('voters')
    op.drop_table('parties')
    # ### end Alembic commands ###
