"""empty message

Revision ID: 9bd589acee94
Revises: e6194ec6e36a
Create Date: 2020-11-04 18:24:48.860606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd589acee94'
down_revision = 'e6194ec6e36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('voted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters', 'voted')
    # ### end Alembic commands ###
